name: Solar System Workflow

on: 
  
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

     
          
       # - name: Archive Test Result
        #  uses: actions/upload-artifact@v4
         # with:
          #  name: Mocha-Test-Result
          #  path: test-results.xml
